# Generated by Django 3.2 on 2022-08-26 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='primary_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingagent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='escrow_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_homes', to='housing.company'),
        ),
        migrations.AddField(
            model_name='home',
            name='excluded_items',
            field=models.ManyToManyField(blank=True, related_name='excluded_items_homes', to='housing.Item'),
        ),
        migrations.AddField(
            model_name='home',
            name='included_items',
            field=models.ManyToManyField(blank=True, related_name='included_items_homes', to='housing.Item'),
        ),
        migrations.AddField(
            model_name='home',
            name='listing_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='housing.listingagent'),
        ),
        migrations.AddField(
            model_name='home',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='housing.property'),
        ),
        migrations.AddField(
            model_name='home',
            name='title_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_homes', to='housing.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='housing.address'),
        ),
    ]
